dataset: IndianPines  # Options: IndianPines, PaviaU, Houston2013, Botswana
in_channels: 200      # Adjust based on dataset (200 for Indian Pines, 103 for PaviaU, etc.)
num_classes: 16       # Adjust based on dataset (16 for Indian Pines, 9 for PaviaU, etc.)
patch_sizes: [5, 7, 9]
num_heads: 4
batch_size: 16
learning_rate: 0.001
epochs: 60
device: cuda